---
# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

- name: delete t1.small device and wait up to 10 minutes for absent state
  hosts: localhost
  tasks:
  - packet_device:
      project_id: e8e311a5-0dbb-4342-bafd-840ff074003e
      hostnames: t1small-test
      facility: sjc1
      state: absent
      wait_timeout: 600

