# Copyright (c) 2018 Intel Corporation
# 
# SPDX-License-Identifier: Apache-2.0
#
# This file contains baseline expectations
# for checked results by checkmetrics tool.
#
# Note: - the values in this file are for example only.
# Actual values will be different according to which system
# the tests are run upon.
# Expect to have to copy/edit this file to match your actual
# system properties.

[[metric]]
name = "boot-times"
type = "json"
description = "measure container lifecycle timings"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".Results | .[] | .\"to-workload\".Result"
checktype = "mean"
minval = 1.3
maxval = 1.5

[[metric]]
name = "memory-footprint"
type = "json"
description = "measure container average footprint"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".Results | .[] | .average.Result"
checktype = "mean"
minval = 245000.0
maxval = 260000.0

[[metric]]
name = "memory-footprint-ksm"
type = "json"
description = "measure container average footprint with KSM"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".Results | .[] | .average.Result"
checktype = "mean"
minval = 100000.0
maxval = 110000.0

